version: "3"
services:
  frontend:
    image: azizul2go/two-tier-frontend-image:latest
    ports:
      - "8080:80"
    depends_on:
      - python-backend-service
  python-backend-service:
    image: azizul2go/two-tier-backend-image:latest
